version: "3"

services:
  reactjest:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/ReactJest
    tty: true
    ports:
      - 5173:5173
    container_name: reactjest
